### PR TITLE
Let's make a module

### PR DESCRIPTION
**Pull request by wasserja**
I'd like to put this into a module that we can put in the gallery. Perhaps we need to change the name and then adjust the naming of the files included.

### CODE REVIEW

**Comment by dfinke** [comment]
The reason I named the repo this way, `known-calendar`, is. When I went to create a new repo, GitHub suggested this.

`Great repository names are short and memorable. Need inspiration? How about congenial-octo-pancake.`

So I used my `NameIT` to randomly generate names.

What are your thoughts?

**Comment by wasserja** [comment]
Naming things is hard. Should we put Chronic in the name somewhere since it is based on the Chronic natural language date parser?

**Comment by dfinke** [comment]
Naming is definitely hard. Putting Chronic in the name might be useful for you and I, we worked on it and know the pieces. To casual users though, seeing it with that or `known-calendar` it probably doesn't matter. Naming it `known-calendar` is off the beaten track, but I kind of like that.

Let me know what you think? Are you you using it? Helpful?

**Comment by wasserja** [comment]
We can stick with the name. I have used the function in testing. I've been working on a restart scheduler that accepts a datetime object, and I think it would be great if i can say restart that computer in 3 hours. So far the testing is working well.

**Comment by dfinke** [comment]
I'll rename the psd1, psm1 and prep it for publishing. Thanks for doing this and testing!

**Pull request merged**
